.TH PYRENAMER 1

.SH NAME
pyRenamer \- Mass file renamer

.SH SYNOPSIS
.B pyrenamer

.SH DESCRIPTION
.B pyrenamer
is a mass file renamer written in PyGTK

.SH HOMEPAGE
http://www.infinicode.org/code/pyrenamer/

.SH "AUTHOR"
This manual page was written by Adolfo Gonzalez Blazquez <code@infinicode\&.org> for \
the GNU/Linux system (but may be used by others)\&. Permission is granted to copy, \
distribute and/or modify this document under the terms of the GNU General Public License, \
Version 2 any later version published by the Free Software Foundation\&.
.PP
pyRenamer (C) 2006-2007, Adolfo Gonzalez Blazquez <code@infinicode\&.org>

